### ISSUE TITLE
eliminate "hit by the bus" risk

### ISSUE THREAD

**Issue by agarwal** [CUFP/cufp.org#33]
At present, @agarwal is the sole person with access to the web server and domain registrar. Put info somewhere secure and give access to additional people.

**Comment by agarwal** [comment]
I'm going to create a google doc with relevant information and give access to a few people. Let me know if anyone has a better idea.

**Comment by agarwal** [comment]
Everyone should have gotten an email with a link to the new document.

**Comment by ekmett** [comment]
Thanks!
