### ISSUE TITLE
announce 2015 conference

### ISSUE THREAD

**Issue by agarwal** [CUFP/cufp.org#37]
Draft of new 2015 page started in e3301be8633ed6924dbdecc184540b49d7b29946, but the following items remain:

- [x] Find nice pictures of Vancouver. Format as needed and remember to add info to the [licenses](http://cufp.org/license.html) file.

- [x] Add program committee members.

- [x] Add Twitter button. Consider where to place it as previous location was a bit awkward.

**Comment by codemiller** [comment]
I have sent a [PR](https://github.com/CUFP/cufp.org/pull/40) with the program committee members and other details for 2015, including the CFP.

**Comment by codemiller** [comment]
I have also added some images of Vancouver, as well as accompanying license information.
