### ISSUE TITLE
fix reference style links

### ISSUE THREAD

**Issue by agarwal** [CUFP/cufp.org#53]
@codemiller I fixed the reference style links [here](http://cufp.org/2015/futures-for-cpp11-at-facebook.html), but I suspect the page isn't being generated the way you intended. Also note reference 5 isn't linked from anywhere.

**Comment by codemiller** [comment]
Thanks - I wasn't sure if that would work but didn't have OCaml locally to
try. The fifth one isn't meant to be linked from anywhere, but Hans still
asked for it to be listed; I'm not sure where to put it now we don't have a
list of links at the end.

**Comment by agarwal** [comment]
I'll just manually duplicate the list of references.
