### ISSUE TITLE
add 2017 tutorial chairs

### ISSUE THREAD

**Issue by agarwal** [CUFP/cufp.org#79]
Tutorial chairs are yet to be determined. Add to front page when known.

**Comment by nushio3** [comment]
Dear agarwal,

Sorry for the late notice. This year's tutorial chairs are  Takayuki Muranushi <muranushi@gmail.com> and Runhang Li . What information may I provide to update the page?

**Comment by objmagic** [comment]
@agarwal @nushio3 

Hi, feel free to add me on the page.

Name: Runhang Li
Affiliation: Twitter, Inc
E-mail: rli @ twitter . com
LinkedIn: https://www.linkedin.com/in/runhang-li-968895115/
GitHub: https://github.com/objmagic

**Comment by agarwal** [comment]
I normally need your name, affiliation, a picture, and link to your website of choice. I got all this information in the pull request, so we're all set. Thanks. Front page has been updated.
