### ISSUE TITLE
update 2017 tutorials description

### ISSUE THREAD

**Issue by agarwal** [CUFP/cufp.org#82]
Front page contains copy/pasted description of tutorials from previous year. It refers too much to tutorials that occurred last year. We should update to be more general and/or to reflect tutorials occurring this year.

cc: @nushio3, @objmagic

**Comment by objmagic** [comment]
Since we haven't decided what tutorials will be (even call for tutorial hasn't happened), I am not sure how to update the tutorials part.

**Comment by objmagic** [comment]
@agarwal also, @nushio3 told me he will be very busy this week. We will work on it later I guess.

**Comment by agarwal** [comment]
I updated slightly by adding "In the past". At least it isn't misleadingly now. We can update further when there is more information about this year's tutorials.

**Comment by nushio3** [comment]
Dear all,

Sorry for the terrible delay, and I'm back. Here is the call for tutorials from the past year.

https://github.com/codemiller/cufp.org/blob/644eed0b2a89232a6a2c2b2957a41b41d6bc17a2/site/2016/call-for-presentations.md

Could you tell me where I can (modify and) upload this year's CFP?

**Comment by agarwal** [comment]
@nushio3 Create the file at the path `site/2017/call-for-tutorials.md`. The file doesn't yet exist. I would copy the one from 2016 and modify that as needed.

I'll create a link to the call-for-tutorials from the front page once you're ready to announce it.

**Comment by objmagic** [comment]
I think this issue can be closed now.

By the way, @agarwal, how can I and @nushio3, tutorial co-chairs, ask https://twitter.com/cufpconference to send out an announcement? Do you happen to own that account? (or we can this offline from GitHub and use e-mail to communicate?)

**Comment by agarwal** [comment]
I have provided @objmagic with login information for CUFP's Twitter account.
